// Categorias e palavras-chave para busca inteligente
export const CATEGORIAS = ["Alinhamento", "Animais", "Ações", "Bancos", "Casa", "Clima", "Comida", "Comunicação", "Comércio", "Corpo & Saúde", "Cursor", "Desenvolvimento", "Dispositivos", "Documentos", "Educação", "Financeiro", "Gráficos", "Imóveis", "Interface", "Lugares", "Marketing", "Multimídia", "Móveis", "Natureza", "Navegação", "Objetos", "Redes Sociais", "Segurança", "Tecnologias", "Tempo", "Usuário", "Veículos"]

export const META = {
  aba: { categoria: "Interface", palavras: ["aba"] },
  acaro: { categoria: "Corpo & Saúde", palavras: ["acaro"] },
  'adicionar-usuario': { categoria: "Usuário", palavras: ["adicionar", "usuario"] },
  agenda: { categoria: "Tempo", palavras: ["agenda"] },
  agibank: { categoria: "Bancos", palavras: ["agibank", "banco", "digital"] },
  agro: { categoria: "Veículos", palavras: ["agricultura", "agro", "fazenda", "rural", "trator"] },
  ajustes: { categoria: "Ações", palavras: ["ajustes"] },
  alfinete: { categoria: "Interface", palavras: ["alfinete"] },
  'alinhar-centro': { categoria: "Alinhamento", palavras: ["alinhar", "centro"] },
  'alinhar-direita': { categoria: "Alinhamento", palavras: ["alinhar", "direita"] },
  'alinhar-esquerda': { categoria: "Alinhamento", palavras: ["alinhar", "esquerda"] },
  'alinhar-justificado': { categoria: "Alinhamento", palavras: ["alinhar", "justificado"] },
  'alto-falante': { categoria: "Multimídia", palavras: ["alto", "falante"] },
  altura: { categoria: "Interface", palavras: ["altura"] },
  alvo: { categoria: "Marketing", palavras: ["alvo"] },
  'alvo-mira': { categoria: "Marketing", palavras: ["alvo", "mira"] },
  ampulheta: { categoria: "Tempo", palavras: ["ampulheta"] },
  analise: { categoria: "Gráficos", palavras: ["analise"] },
  analytics: { categoria: "Gráficos", palavras: ["analytics"] },
  antecipacoes: { categoria: "Financeiro", palavras: ["advances", "antecipacoes"] },
  'aperto-maos': { categoria: "Corpo & Saúde", palavras: ["aperto", "maos", "negociacao"] },
  arquivar: { categoria: "Documentos", palavras: ["arquivar"] },
  arquivo: { categoria: "Documentos", palavras: ["arquivo"] },
  arquivos: { categoria: "Documentos", palavras: ["arquivos"] },
  arrastar: { categoria: "Navegação", palavras: ["arrastar"] },
  arroba: { categoria: "Redes Sociais", palavras: ["arroba"] },
  'arroba-destaque': { categoria: "Redes Sociais", palavras: ["arroba", "destaque"] },
  asaas: { categoria: "Bancos", palavras: ["asaas", "banco", "cobranca", "gateway", "pagamento"] },
  'assinatura-premium': { categoria: "Documentos", palavras: ["assinatura", "premium"] },
  assinaturas: { categoria: "Documentos", palavras: ["assinaturas"] },
  asteristico: { categoria: "Interface", palavras: ["asteristico"] },
  'asteristico-2': { categoria: "Interface", palavras: ["asteristico"] },
  atencao: { categoria: "Objetos", palavras: ["atencao", "aviso"] },
  atendimento: { categoria: "Comunicação", palavras: ["atendimento"] },
  atualizar: { categoria: "Ações", palavras: ["atualizar", "recarregar", "resetar"] },
  avatar: { categoria: "Usuário", palavras: ["avatar"] },
  avenue: { categoria: "Bancos", palavras: ["avenue", "banco", "corretora", "internacional", "investimento"] },
  aviao: { categoria: "Veículos", palavras: ["aeroporto", "aviao", "turismo", "viagem", "viajar", "voo"] },
  avisos: { categoria: "Comunicação", palavras: ["avisos"] },
  backup: { categoria: "Dispositivos", palavras: ["backup"] },
  balanca: { categoria: "Financeiro", palavras: ["balanca", "saldo"] },
  bambu: { categoria: "Natureza", palavras: ["bambu"] },
  banco: { categoria: "Financeiro", palavras: ["banco"] },
  bancodobrasil: { categoria: "Bancos", palavras: ["banco", "bancodobrasil", "bb"] },
  banheira: { categoria: "Imóveis", palavras: ["banheira"] },
  barco: { categoria: "Veículos", palavras: ["barco", "boat"] },
  bebe: { categoria: "Corpo & Saúde", palavras: ["bebe"] },
  bicicletario: { categoria: "Imóveis", palavras: ["bicicletario"] },
  biomecanica: { categoria: "Corpo & Saúde", palavras: ["biomecanica"] },
  biometria: { categoria: "Usuário", palavras: ["biometria"] },
  bitcoin: { categoria: "Financeiro", palavras: ["bitcoin"] },
  blindado: { categoria: "Segurança", palavras: ["blindado"] },
  blog: { categoria: "Documentos", palavras: ["blog"] },
  bloquear: { categoria: "Ações", palavras: ["bloquear"] },
  bmg: { categoria: "Bancos", palavras: ["banco", "bmg"] },
  boca: { categoria: "Corpo & Saúde", palavras: ["boca"] },
  boleto: { categoria: "Financeiro", palavras: ["boleto"] },
  bonus: { categoria: "Comércio", palavras: ["bonus"] },
  borda: { categoria: "Interface", palavras: ["borda"] },
  'borda-dupla': { categoria: "Interface", palavras: ["borda", "dupla"] },
  'borda-solida': { categoria: "Interface", palavras: ["borda", "solida"] },
  'borda-tracejada': { categoria: "Interface", palavras: ["borda", "tracejada"] },
  braco: { categoria: "Corpo & Saúde", palavras: ["braco"] },
  bradesco: { categoria: "Bancos", palavras: ["banco", "bradesco"] },
  brinquedoteca: { categoria: "Imóveis", palavras: ["brinquedoteca"] },
  bs2: { categoria: "Bancos", palavras: ["banco", "bs2"] },
  btg: { categoria: "Bancos", palavras: ["banco", "btg", "investimento"] },
  bv: { categoria: "Bancos", palavras: ["banco", "bv", "votorantim"] },
  c6: { categoria: "Bancos", palavras: ["banco", "c6", "digital"] },
  cabra: { categoria: "Animais", palavras: ["cabra"] },
  cachorro: { categoria: "Animais", palavras: ["cachorro"] },
  cadeado: { categoria: "Segurança", palavras: ["bloqueio", "cadeado", "lock", "privado", "protegido", "seguranca", "senha"] },
  'cadeado-aberto': { categoria: "Segurança", palavras: ["aberto", "cadeado", "desbloqueado", "liberado"] },
  'cadeado-redondo': { categoria: "Segurança", palavras: ["cadeado", "redondo"] },
  cadeira: { categoria: "Móveis", palavras: ["cadeira"] },
  'cadeira-madeira': { categoria: "Móveis", palavras: ["cadeira", "madeira"] },
  caixa: { categoria: "Bancos", palavras: ["banco", "caixa", "caixa-economica", "cef"] },
  calculadora: { categoria: "Financeiro", palavras: ["calculadora"] },
  calendario: { categoria: "Tempo", palavras: ["agenda", "agendar", "calendario", "data", "dia", "evento", "mes"] },
  cama: { categoria: "Móveis", palavras: ["cama"] },
  'cama-casal': { categoria: "Casa", palavras: ["cama", "casal", "colchao", "dormir", "movel", "quarto"] },
  'cama-solteiro': { categoria: "Móveis", palavras: ["cama", "solteiro"] },
  camera: { categoria: "Multimídia", palavras: ["camera", "filmar", "foto", "fotografia", "imagem", "video"] },
  caminhao: { categoria: "Veículos", palavras: ["caminhao", "carga", "frete", "transporte", "veiculo"] },
  'caminhao-entrega': { categoria: "Veículos", palavras: ["caminhao", "entrega"] },
  caminhonete: { categoria: "Veículos", palavras: ["caminhonete"] },
  'caminhonete-cabine-dupla': { categoria: "Veículos", palavras: ["cabine", "caminhonete", "dupla"] },
  camiseta: { categoria: "Comércio", palavras: ["camiseta"] },
  campo: { categoria: "Desenvolvimento", palavras: ["campo"] },
  caneca: { categoria: "Comércio", palavras: ["caneca"] },
  caneta: { categoria: "Alinhamento", palavras: ["caneta", "lapis"] },
  'canto-arredondado': { categoria: "Interface", palavras: ["arredondado", "canto"] },
  'capacete-protecao': { categoria: "Corpo & Saúde", palavras: ["capacete", "protecao"] },
  carne: { categoria: "Comida", palavras: ["carne"] },
  carrinho: { categoria: "Comércio", palavras: ["carrinho"] },
  'carrinho-bebe': { categoria: "Comércio", palavras: ["bebe", "carrinho"] },
  carro: { categoria: "Veículos", palavras: ["automovel", "carro", "dirigir", "transporte", "veiculo"] },
  'carro-banco': { categoria: "Financeiro", palavras: ["banco", "carro"] },
  cartao: { categoria: "Financeiro", palavras: ["card", "cartao", "credito", "debito", "pagamento"] },
  'cartas-jogo': { categoria: "Objetos", palavras: ["cartas", "jogo"] },
  carteira: { categoria: "Financeiro", palavras: ["carteira"] },
  casa: { categoria: "Casa", palavras: ["casa", "home", "imovel", "inicio", "residencia"] },
  'casa-dinheiro': { categoria: "Imóveis", palavras: ["casa", "dinheiro"] },
  'casa-estilo': { categoria: "Imóveis", palavras: ["casa", "estilo"] },
  'casa-fina': { categoria: "Imóveis", palavras: ["casa", "casa-dois", "casa-linha", "fina"] },
  'casa-mao': { categoria: "Imóveis", palavras: ["casa", "mao"] },
  'casa-quadrados': { categoria: "Imóveis", palavras: ["casa", "quadrados"] },
  'casa-tamanho': { categoria: "Imóveis", palavras: ["casa", "tamanho"] },
  catalogo: { categoria: "Documentos", palavras: ["catalogo"] },
  cavalo: { categoria: "Animais", palavras: ["cavalo"] },
  celular: { categoria: "Dispositivos", palavras: ["celular"] },
  cerebro: { categoria: "Corpo & Saúde", palavras: ["cerebro"] },
  'cerebro-ia': { categoria: "Tecnologias", palavras: ["cerebro", "ia"] },
  certificado: { categoria: "Documentos", palavras: ["certificado"] },
  certo: { categoria: "Interface", palavras: ["certo"] },
  'cesta-basquete': { categoria: "Educação", palavras: ["basquete", "cesta"] },
  chave: { categoria: "Objetos", palavras: ["acesso", "chave", "seguranca", "senha", "solucao"] },
  check: { categoria: "Interface", palavras: ["aprovado", "check", "confirmar", "correto", "feito", "ok", "sucesso"] },
  'check-circulo': { categoria: "Interface", palavras: ["check", "circulo"] },
  'check-duplo': { categoria: "Interface", palavras: ["check", "duplo"] },
  'check-escudo': { categoria: "Interface", palavras: ["check", "escudo"] },
  'check-limpo': { categoria: "Interface", palavras: ["check", "limpo"] },
  'check-linha': { categoria: "Interface", palavras: ["check", "linha"] },
  'check-onda': { categoria: "Interface", palavras: ["check", "onda"] },
  'check-redondo': { categoria: "Interface", palavras: ["check", "check-cheio", "redondo"] },
  chuveiro: { categoria: "Imóveis", palavras: ["chuveiro"] },
  cinema: { categoria: "Multimídia", palavras: ["cinema"] },
  citacao: { categoria: "Comunicação", palavras: ["citacao"] },
  classico: { categoria: "Veículos", palavras: ["classico"] },
  'cliente-aniversario': { categoria: "Usuário", palavras: ["aniversario", "cliente"] },
  clientes: { categoria: "Usuário", palavras: ["clientes", "contatos", "pacientes"] },
  'clientes-estrela': { categoria: "Usuário", palavras: ["clientes", "estrela"] },
  cobrancas: { categoria: "Financeiro", palavras: ["cobrancas"] },
  codigo: { categoria: "Desenvolvimento", palavras: ["codigo"] },
  'codigo-bloco': { categoria: "Desenvolvimento", palavras: ["bloco", "codigo"] },
  'codigo-de-barras': { categoria: "Desenvolvimento", palavras: ["barras", "codigo", "de", "ean", "produto", "scanner"] },
  coelho: { categoria: "Animais", palavras: ["coelho"] },
  colaborador: { categoria: "Usuário", palavras: ["colaborador"] },
  coluna: { categoria: "Interface", palavras: ["coluna"] },
  compacto: { categoria: "Veículos", palavras: ["compacto"] },
  compartilhar: { categoria: "Ações", palavras: ["compartilhar", "dividir", "enviar", "espalhar", "share"] },
  compradores: { categoria: "Usuário", palavras: ["compradores"] },
  computador: { categoria: "Dispositivos", palavras: ["computador"] },
  contrato: { categoria: "Documentos", palavras: ["contrato"] },
  'contrato-assinar': { categoria: "Documentos", palavras: ["assinar", "contrato"] },
  'contrato-dinheiro': { categoria: "Financeiro", palavras: ["contrato", "dinheiro"] },
  contratos: { categoria: "Documentos", palavras: ["contratos"] },
  conveniencias: { categoria: "Imóveis", palavras: ["conveniencias"] },
  conversa: { categoria: "Comunicação", palavras: ["conversa"] },
  conversas: { categoria: "Comunicação", palavras: ["conversas"] },
  conversivel: { categoria: "Veículos", palavras: ["conversivel"] },
  copiar: { categoria: "Ações", palavras: ["copiar"] },
  cora: { categoria: "Bancos", palavras: ["banco", "cora", "digital", "pj"] },
  coracao: { categoria: "Objetos", palavras: ["amor", "coracao", "curtir", "favorito", "gostar", "like", "romance", "saude"] },
  'coracao-circulo': { categoria: "Objetos", palavras: ["circulo", "coracao"] },
  coroa: { categoria: "Objetos", palavras: ["coroa", "melhor", "premium", "realeza", "rei", "top", "vip"] },
  costas: { categoria: "Corpo & Saúde", palavras: ["costas"] },
  crescimento: { categoria: "Marketing", palavras: ["crescimento"] },
  cronometro: { categoria: "Tempo", palavras: ["cronometro"] },
  cubo: { categoria: "Objetos", palavras: ["cubo", "cubo-3d"] },
  cupe: { categoria: "Veículos", palavras: ["cupe"] },
  cursor: { categoria: "Cursor", palavras: ["cursor"] },
  'cursor-ajuda': { categoria: "Cursor", palavras: ["ajuda", "cursor"] },
  'cursor-bloqueado': { categoria: "Cursor", palavras: ["bloqueado", "cursor"] },
  'cursor-espera': { categoria: "Cursor", palavras: ["cursor", "espera"] },
  'cursor-mira': { categoria: "Cursor", palavras: ["cursor", "mira"] },
  'cursor-mover': { categoria: "Cursor", palavras: ["cursor", "cursor-redimensionar", "mover"] },
  'cursor-ponteiro': { categoria: "Cursor", palavras: ["cursor", "ponteiro"] },
  'cursor-progresso': { categoria: "Cursor", palavras: ["cursor", "progresso"] },
  'cursor-proibido': { categoria: "Cursor", palavras: ["cursor", "proibido"] },
  'cursor-redimensionar-linha': { categoria: "Cursor", palavras: ["cursor", "linha", "redimensionar"] },
  'cursor-rolar': { categoria: "Cursor", palavras: ["cursor", "cursor-mover-tudo", "rolar"] },
  'cursor-texto': { categoria: "Cursor", palavras: ["cursor", "texto"] },
  curva: { categoria: "Navegação", palavras: ["curva"] },
  dashboard: { categoria: "Interface", palavras: ["dashboard"] },
  debug: { categoria: "Desenvolvimento", palavras: ["debug"] },
  'deck-molhado': { categoria: "Imóveis", palavras: ["deck", "molhado"] },
  dedo: { categoria: "Interface", palavras: ["dedo"] },
  desfazer: { categoria: "Ações", palavras: ["desfazer"] },
  design: { categoria: "Alinhamento", palavras: ["design"] },
  desktop: { categoria: "Dispositivos", palavras: ["desktop"] },
  desligar: { categoria: "Interface", palavras: ["desligar", "power-off", "sair"] },
  despesas: { categoria: "Financeiro", palavras: ["despesas"] },
  detalhes: { categoria: "Interface", palavras: ["detalhes"] },
  diamante: { categoria: "Objetos", palavras: ["diamante", "joia", "luxo", "premium", "valioso", "vip"] },
  digio: { categoria: "Bancos", palavras: ["banco", "digio", "digital"] },
  digitalocean: { categoria: "Tecnologias", palavras: ["cloud", "devops", "digitalocean", "hospedagem", "servidor", "tech", "tech-digitalocean"] },
  dinheiro: { categoria: "Financeiro", palavras: ["cash", "dinheiro", "grana", "pagamento", "renda", "salario", "valor"] },
  doacao: { categoria: "Natureza", palavras: ["doacao", "vida"] },
  docker: { categoria: "Tecnologias", palavras: ["container", "devops", "docker", "tech", "tech-docker", "tecnologia"] },
  documento: { categoria: "Documentos", palavras: ["documento", "nota"] },
  'documento-atencao': { categoria: "Documentos", palavras: ["atencao", "documento"] },
  'documento-check': { categoria: "Interface", palavras: ["check", "documento"] },
  'documento-fiscal': { categoria: "Documentos", palavras: ["documento", "fiscal"] },
  'documento-linhas': { categoria: "Documentos", palavras: ["documento", "linhas"] },
  download: { categoria: "Ações", palavras: ["baixar", "download", "salvar", "transferir"] },
  duvida: { categoria: "Objetos", palavras: ["duvida", "interrogacao"] },
  'duvida-quadrado': { categoria: "Imóveis", palavras: ["duvida", "quadrado"] },
  editar: { categoria: "Ações", palavras: ["alterar", "edit", "editar", "escrever", "lapis", "modificar"] },
  efibank: { categoria: "Bancos", palavras: ["banco", "efibank", "gateway", "gerencianet", "pagamento"] },
  elevador: { categoria: "Imóveis", palavras: ["elevador"] },
  'elevador-social': { categoria: "Imóveis", palavras: ["elevador", "social"] },
  empresa: { categoria: "Casa", palavras: ["empresa"] },
  engrenagem: { categoria: "Objetos", palavras: ["configurar", "engrenagem", "maquinas", "servicos"] },
  enquadrar: { categoria: "Interface", palavras: ["captacao", "captura", "enquadrar"] },
  entrar: { categoria: "Usuário", palavras: ["entrar"] },
  entrega: { categoria: "Veículos", palavras: ["entrega"] },
  'envelope-1': { categoria: "Comunicação", palavras: ["1", "envelope"] },
  'envelope-2': { categoria: "Comunicação", palavras: ["envelope"] },
  'envelope-3': { categoria: "Comunicação", palavras: ["envelope", "envelope-4"] },
  enviar: { categoria: "Ações", palavras: ["enviar"] },
  equipe: { categoria: "Usuário", palavras: ["equipe"] },
  escala: { categoria: "Interface", palavras: ["escala"] },
  escavadeira: { categoria: "Veículos", palavras: ["escavadeira"] },
  escola: { categoria: "Educação", palavras: ["escola"] },
  escudo: { categoria: "Segurança", palavras: ["defesa", "escudo", "garantia", "protecao", "seguranca", "seguro"] },
  'escudo-check': { categoria: "Interface", palavras: ["check", "escudo"] },
  espaco: { categoria: "Imóveis", palavras: ["espaco"] },
  'espaco-gourmet': { categoria: "Imóveis", palavras: ["espaco", "gourmet"] },
  espelhar: { categoria: "Navegação", palavras: ["espelhar"] },
  esportivo: { categoria: "Veículos", palavras: ["esportivo"] },
  esquilo: { categoria: "Animais", palavras: ["esquilo"] },
  estrela: { categoria: "Objetos", palavras: ["avaliacao", "destaque", "estrela", "favorito", "premium", "rating"] },
  expandir: { categoria: "Navegação", palavras: ["expandir"] },
  exportar: { categoria: "Ações", palavras: ["exportar"] },
  extensao: { categoria: "Desenvolvimento", palavras: ["extensao"] },
  externo: { categoria: "Navegação", palavras: ["externo"] },
  facebook: { categoria: "Redes Sociais", palavras: ["facebook"] },
  faceid: { categoria: "Usuário", palavras: ["faceid"] },
  fatura: { categoria: "Financeiro", palavras: ["fatura"] },
  fechar: { categoria: "Ações", palavras: ["fechar"] },
  feedback: { categoria: "Comunicação", palavras: ["feedback"] },
  feliz: { categoria: "Corpo & Saúde", palavras: ["feliz"] },
  feminino: { categoria: "Usuário", palavras: ["feminino"] },
  ferramenta: { categoria: "Objetos", palavras: ["ferramenta"] },
  figma: { categoria: "Tecnologias", palavras: ["design", "ferramenta", "figma", "prototipo", "tech", "tech-figma", "ui"] },
  filme: { categoria: "Multimídia", palavras: ["filme"] },
  filtro: { categoria: "Ações", palavras: ["filtrar", "filtro"] },
  'filtro-limpar': { categoria: "Ações", palavras: ["filtro", "limpar"] },
  financeiro: { categoria: "Financeiro", palavras: ["financeiro", "moeda", "precificacao", "vendas"] },
  'fitness-ao-ar-livre': { categoria: "Corpo & Saúde", palavras: ["ao", "ar", "fitness", "livre"] },
  flor: { categoria: "Natureza", palavras: ["flor", "jardim", "natureza", "planta", "primavera"] },
  fogo: { categoria: "Objetos", palavras: ["fogo"] },
  foguete: { categoria: "Marketing", palavras: ["crescer", "foguete", "lancar", "rapido", "startup"] },
  folha: { categoria: "Natureza", palavras: ["folha"] },
  folhas: { categoria: "Natureza", palavras: ["folhas"] },
  fonte: { categoria: "Alinhamento", palavras: ["fonte"] },
  formas: { categoria: "Interface", palavras: ["formas"] },
  formatura: { categoria: "Educação", palavras: ["formatura"] },
  formulario: { categoria: "Desenvolvimento", palavras: ["formulario"] },
  fornecedores: { categoria: "Usuário", palavras: ["fornecedores"] },
  fotos: { categoria: "Multimídia", palavras: ["fotos"] },
  frutas: { categoria: "Comida", palavras: ["frutas"] },
  galinha: { categoria: "Animais", palavras: ["galinha"] },
  gato: { categoria: "Animais", palavras: ["gato"] },
  germe: { categoria: "Corpo & Saúde", palavras: ["germe"] },
  girar: { categoria: "Navegação", palavras: ["girar"] },
  github: { categoria: "Tecnologias", palavras: ["codigo", "git", "github", "octocat", "repositorio", "tech", "versionamento"] },
  globo: { categoria: "Lugares", palavras: ["global", "globo", "idioma", "internet", "mundo", "planeta", "web"] },
  gota: { categoria: "Clima", palavras: ["gota"] },
  'gota-tinta': { categoria: "Alinhamento", palavras: ["gota", "tinta"] },
  grafico: { categoria: "Gráficos", palavras: ["grafico"] },
  'grafico-dinheiro': { categoria: "Financeiro", palavras: ["dinheiro", "grafico"] },
  graficos: { categoria: "Gráficos", palavras: ["analise", "dados", "estatistica", "graficos", "metrica", "relatorio"] },
  'guarda-chuva': { categoria: "Clima", palavras: ["chuva", "guarda", "umbrella"] },
  hashtag: { categoria: "Interface", palavras: ["hashtag"] },
  hatch: { categoria: "Veículos", palavras: ["carro", "hatch", "veiculo"] },
  headset: { categoria: "Comunicação", palavras: ["atendimento", "headset", "suporte"] },
  helicoptero: { categoria: "Veículos", palavras: ["aeronave", "helicoptero", "transporte", "voar"] },
  historico: { categoria: "Gráficos", palavras: ["historico"] },
  hospital: { categoria: "Lugares", palavras: ["hospital"] },
  ia: { categoria: "Tecnologias", palavras: ["ia"] },
  'ia-brilho': { categoria: "Tecnologias", palavras: ["brilho", "ia"] },
  identidade: { categoria: "Usuário", palavras: ["identidade"] },
  idioma: { categoria: "Interface", palavras: ["idioma"] },
  igreja: { categoria: "Lugares", palavras: ["igreja"] },
  imagem: { categoria: "Multimídia", palavras: ["foto", "imagem"] },
  importar: { categoria: "Ações", palavras: ["importar"] },
  imprimir: { categoria: "Ações", palavras: ["imprimir"] },
  infinitepay: { categoria: "Bancos", palavras: ["banco", "infinitepay", "maquininha", "pagamento"] },
  infinito: { categoria: "Interface", palavras: ["infinito"] },
  info: { categoria: "Objetos", palavras: ["info"] },
  ingresso: { categoria: "Comércio", palavras: ["ingresso"] },
  instagram: { categoria: "Redes Sociais", palavras: ["instagram"] },
  institucional: { categoria: "Casa", palavras: ["institucional"] },
  integracoes: { categoria: "Desenvolvimento", palavras: ["integracoes"] },
  inter: { categoria: "Bancos", palavras: ["banco", "digital", "inter", "laranja"] },
  internet: { categoria: "Interface", palavras: ["internet"] },
  italico: { categoria: "Alinhamento", palavras: ["italico"] },
  itau: { categoria: "Bancos", palavras: ["banco", "itau"] },
  iugu: { categoria: "Bancos", palavras: ["banco", "cobranca", "gateway", "iugu", "pagamento"] },
  jardim: { categoria: "Imóveis", palavras: ["jardim"] },
  javascript: { categoria: "Tecnologias", palavras: ["codigo", "javascript", "js", "linguagem", "programacao", "tech", "tech-javascript"] },
  'jet-ski': { categoria: "Veículos", palavras: ["aquatico", "barco", "jet", "mar", "nautico", "ski"] },
  lampada: { categoria: "Objetos", palavras: ["lampada"] },
  lancha: { categoria: "Veículos", palavras: ["barco", "lancha", "mar", "nautico"] },
  laranja: { categoria: "Comida", palavras: ["laranja"] },
  layout: { categoria: "Desenvolvimento", palavras: ["layout"] },
  like: { categoria: "Objetos", palavras: ["like"] },
  limao: { categoria: "Comida", palavras: ["limao"] },
  limousine: { categoria: "Veículos", palavras: ["limousine"] },
  link: { categoria: "Interface", palavras: ["link"] },
  linkedin: { categoria: "Redes Sociais", palavras: ["linkedin"] },
  lista: { categoria: "Interface", palavras: ["lista"] },
  livro: { categoria: "Documentos", palavras: ["livro"] },
  livros: { categoria: "Documentos", palavras: ["livros"] },
  lixeira: { categoria: "Ações", palavras: ["apagar", "deletar", "delete", "excluir", "lixeira", "lixo", "remover"] },
  loading: { categoria: "Interface", palavras: ["loading"] },
  'local-estrela': { categoria: "Lugares", palavras: ["estrela", "local"] },
  localizacao: { categoria: "Lugares", palavras: ["localizacao", "pino"] },
  lotus: { categoria: "Objetos", palavras: ["lotus"] },
  lua: { categoria: "Clima", palavras: ["dark", "dormir", "escuro", "lua", "noite"] },
  'lua-estrelas': { categoria: "Clima", palavras: ["estrelas", "lua"] },
  lupa: { categoria: "Ações", palavras: ["busca", "buscar", "lupa", "pesquisar", "procurar", "search", "zoom"] },
  maca: { categoria: "Comida", palavras: ["maca"] },
  mais: { categoria: "Ações", palavras: ["add", "adicionar", "criar", "incluir", "mais", "novo", "soma"] },
  'mais-caixa': { categoria: "Ações", palavras: ["caixa", "mais"] },
  'mais-circulo': { categoria: "Ações", palavras: ["circulo", "mais"] },
  'mais-fino': { categoria: "Ações", palavras: ["fino", "mais"] },
  manual: { categoria: "Documentos", palavras: ["manual"] },
  'mao-dinheiro': { categoria: "Financeiro", palavras: ["dinheiro", "mao"] },
  'maos-juntas': { categoria: "Corpo & Saúde", palavras: ["acordo", "colaboracao", "juntas", "maos", "obrigado", "parceria", "uniao"] },
  'maos-unidas': { categoria: "Corpo & Saúde", palavras: ["maos", "unidas"] },
  mapa: { categoria: "Lugares", palavras: ["mapa"] },
  marcador: { categoria: "Lugares", palavras: ["marcador"] },
  martelo: { categoria: "Objetos", palavras: ["martelo"] },
  'martelo-juiz': { categoria: "Objetos", palavras: ["juiz", "martelo"] },
  masculino: { categoria: "Usuário", palavras: ["masculino"] },
  medalha: { categoria: "Objetos", palavras: ["conquista", "medalha", "premio", "ranking", "reconhecimento"] },
  'medalha-aprovada': { categoria: "Objetos", palavras: ["aprovada", "medalha"] },
  megafone: { categoria: "Multimídia", palavras: ["megafone"] },
  'megafone-anuncio': { categoria: "Multimídia", palavras: ["anuncio", "megafone"] },
  menos: { categoria: "Ações", palavras: ["diminuir", "menos", "remover", "subtrair", "tirar"] },
  'menos-caixa': { categoria: "Ações", palavras: ["caixa", "menos"] },
  menu: { categoria: "Navegação", palavras: ["menu"] },
  'menu-curto': { categoria: "Navegação", palavras: ["curto", "menu"] },
  mercadopago: { categoria: "Bancos", palavras: ["banco", "carteira", "mercado-livre", "mercadopago", "pagamento"] },
  mercantil: { categoria: "Bancos", palavras: ["banco", "mercantil"] },
  microfone: { categoria: "Multimídia", palavras: ["microfone"] },
  microonibus: { categoria: "Veículos", palavras: ["microonibus"] },
  migrar: { categoria: "Ações", palavras: ["migrar"] },
  minimizar: { categoria: "Interface", palavras: ["minimizar"] },
  minivan: { categoria: "Veículos", palavras: ["minivan"] },
  modelo: { categoria: "Interface", palavras: ["modelo"] },
  modo: { categoria: "Interface", palavras: ["modo"] },
  mofo: { categoria: "Corpo & Saúde", palavras: ["mofo"] },
  monitor: { categoria: "Dispositivos", palavras: ["imac", "monitor", "monitor-grafico"] },
  'monitor-info': { categoria: "Dispositivos", palavras: ["info", "monitor"] },
  morango: { categoria: "Comida", palavras: ["morango"] },
  moto: { categoria: "Veículos", palavras: ["duas-rodas", "moto", "motocicleta", "veiculo"] },
  'moto-chopper': { categoria: "Veículos", palavras: ["chopper", "moto"] },
  'moto-classic': { categoria: "Veículos", palavras: ["classic", "moto"] },
  'moto-cross': { categoria: "Veículos", palavras: ["cross", "moto"] },
  'moto-touring': { categoria: "Veículos", palavras: ["moto", "touring"] },
  mundo: { categoria: "Lugares", palavras: ["mundo"] },
  musica: { categoria: "Multimídia", palavras: ["musica"] },
  n8n: { categoria: "Tecnologias", palavras: ["automacao", "integracao", "n8n", "no-code", "tech", "tech-n8n", "workflow"] },
  negocio: { categoria: "Casa", palavras: ["negocio"] },
  neon: { categoria: "Bancos", palavras: ["banco", "digital", "neon"] },
  next: { categoria: "Bancos", palavras: ["banco", "digital", "next"] },
  ngcash: { categoria: "Bancos", palavras: ["banco", "carteira", "ngcash", "pagamento"] },
  nginx: { categoria: "Tecnologias", palavras: ["devops", "nginx", "proxy", "servidor", "tech", "tech-nginx", "web"] },
  nomad: { categoria: "Bancos", palavras: ["banco", "digital", "dolar", "internacional", "nomad"] },
  notas: { categoria: "Documentos", palavras: ["notas"] },
  'notas-fiscais': { categoria: "Documentos", palavras: ["fiscais", "notas"] },
  noticias: { categoria: "Documentos", palavras: ["noticias"] },
  npm: { categoria: "Tecnologias", palavras: ["biblioteca", "dependencia", "node", "npm", "pacote", "registro", "tech"] },
  nubank: { categoria: "Bancos", palavras: ["banco", "digital", "nubank", "roxo"] },
  nuvem: { categoria: "Clima", palavras: ["nuvem", "nuvem-cheio"] },
  nuxt: { categoria: "Tecnologias", palavras: ["framework", "frontend", "javascript", "nuxt", "tech", "tech-nuxt", "vue"] },
  oculto: { categoria: "Interface", palavras: ["oculto"] },
  olho: { categoria: "Interface", palavras: ["olho", "visivel"] },
  ombro: { categoria: "Corpo & Saúde", palavras: ["ombro"] },
  ondas: { categoria: "Clima", palavras: ["ondas"] },
  onibus: { categoria: "Veículos", palavras: ["bus", "coletivo", "onibus", "transporte", "veiculo"] },
  online: { categoria: "Interface", palavras: ["online"] },
  opcoes: { categoria: "Ações", palavras: ["bolinhas", "opcoes"] },
  orcamentos: { categoria: "Financeiro", palavras: ["orcamentos"] },
  'ordem-alfabetica-a-z': { categoria: "Ações", palavras: ["a", "alfabetica", "ordem", "z"] },
  'ordem-alfabetica-z-a': { categoria: "Ações", palavras: ["a", "alfabetica", "ordem", "z"] },
  ordenar: { categoria: "Ações", palavras: ["ordenar"] },
  'ordenar-az': { categoria: "Ações", palavras: ["az", "ordenar"] },
  'ordenar-baixo': { categoria: "Ações", palavras: ["baixo", "ordenar"] },
  ordens: { categoria: "Documentos", palavras: ["ordens"] },
  original: { categoria: "Bancos", palavras: ["banco", "digital", "original"] },
  otimizacao: { categoria: "Gráficos", palavras: ["otimizacao"] },
  pagbank: { categoria: "Bancos", palavras: ["banco", "maquininha", "pagamento", "pagbank", "pagseguro"] },
  paleta: { categoria: "Alinhamento", palavras: ["paleta"] },
  pan: { categoria: "Bancos", palavras: ["banco", "pan"] },
  papagaio: { categoria: "Animais", palavras: ["papagaio"] },
  parceiro: { categoria: "Usuário", palavras: ["parceiro"] },
  parques: { categoria: "Imóveis", palavras: ["parques"] },
  pasta: { categoria: "Documentos", palavras: ["pasta"] },
  pata: { categoria: "Animais", palavras: ["pata"] },
  patinete: { categoria: "Veículos", palavras: ["patinete"] },
  pausa: { categoria: "Multimídia", palavras: ["pausa"] },
  paypal: { categoria: "Bancos", palavras: ["banco", "gateway", "internacional", "pagamento", "paypal"] },
  peito: { categoria: "Corpo & Saúde", palavras: ["peito"] },
  perfil: { categoria: "Usuário", palavras: ["perfil"] },
  perna: { categoria: "Corpo & Saúde", palavras: ["perna"] },
  personalizar: { categoria: "Ações", palavras: ["personalizar"] },
  perua: { categoria: "Veículos", palavras: ["perua"] },
  'pessoa-laptop': { categoria: "Usuário", palavras: ["laptop", "pessoa"] },
  pessoas: { categoria: "Usuário", palavras: ["afiliados", "pessoas"] },
  'pessoas-grupo': { categoria: "Usuário", palavras: ["corretor", "grupo", "pessoas"] },
  picpay: { categoria: "Bancos", palavras: ["banco", "carteira", "pagamento", "picpay"] },
  pintinho: { categoria: "Animais", palavras: ["pintinho"] },
  piscina: { categoria: "Imóveis", palavras: ["piscina"] },
  'piscina-adulto': { categoria: "Imóveis", palavras: ["adulto", "piscina"] },
  pix: { categoria: "Financeiro", palavras: ["dinheiro", "pagamento", "pix", "transferencia"] },
  play: { categoria: "Multimídia", palavras: ["play", "play-dois"] },
  'play-cheio': { categoria: "Multimídia", palavras: ["cheio", "play"] },
  policia: { categoria: "Usuário", palavras: ["policia"] },
  poltrona: { categoria: "Móveis", palavras: ["cadeira", "estofado", "movel", "poltrona"] },
  'poltrona-luxo': { categoria: "Móveis", palavras: ["luxo", "poltrona"] },
  pontinhos: { categoria: "Interface", palavras: ["pontinhos"] },
  porcentagem: { categoria: "Financeiro", palavras: ["porcentagem"] },
  porco: { categoria: "Animais", palavras: ["porco"] },
  portaria: { categoria: "Imóveis", palavras: ["portaria"] },
  posvenda: { categoria: "Gráficos", palavras: ["posvenda"] },
  'pouco-estoque': { categoria: "Gráficos", palavras: ["estoque", "pouco"] },
  'prancheta-assinar': { categoria: "Financeiro", palavras: ["assinar", "prancheta"] },
  preco: { categoria: "Financeiro", palavras: ["preco"] },
  predio: { categoria: "Casa", palavras: ["predio"] },
  premium: { categoria: "Objetos", palavras: ["premium"] },
  presente: { categoria: "Comércio", palavras: ["aniversario", "brinde", "gift", "oferta", "presente", "regalo"] },
  produtos: { categoria: "Comércio", palavras: ["produtos"] },
  proibido: { categoria: "Ações", palavras: ["proibido"] },
  projetos: { categoria: "Interface", palavras: ["projetos"] },
  proposta: { categoria: "Documentos", palavras: ["proposta"] },
  propostas: { categoria: "Documentos", palavras: ["propostas"] },
  proprietario: { categoria: "Casa", palavras: ["proprietario"] },
  puzzle: { categoria: "Desenvolvimento", palavras: ["puzzle"] },
  quadrado: { categoria: "Imóveis", palavras: ["quadrado"] },
  quadrados: { categoria: "Imóveis", palavras: ["quadrados"] },
  quadros: { categoria: "Interface", palavras: ["quadros"] },
  raio: { categoria: "Clima", palavras: ["eletrico", "energia", "flash", "potencia", "raio", "rapido", "velocidade"] },
  'raio-relampago': { categoria: "Clima", palavras: ["raio", "relampago"] },
  ranking: { categoria: "Gráficos", palavras: ["ranking"] },
  real: { categoria: "Financeiro", palavras: ["real"] },
  receitas: { categoria: "Financeiro", palavras: ["receita", "receitas"] },
  recibo: { categoria: "Financeiro", palavras: ["recibo"] },
  refeicao: { categoria: "Comida", palavras: ["refeicao"] },
  regua: { categoria: "Interface", palavras: ["regua"] },
  'regua-reta': { categoria: "Interface", palavras: ["regua", "reta"] },
  relatorio: { categoria: "Documentos", palavras: ["relatorio"] },
  relogio: { categoria: "Tempo", palavras: ["cronometro", "hora", "horario", "relogio", "tempo"] },
  'renda-extra': { categoria: "Financeiro", palavras: ["extra", "renda"] },
  repetir: { categoria: "Ações", palavras: ["repetir"] },
  responsivo: { categoria: "Desenvolvimento", palavras: ["responsivo"] },
  'reticencias-circulo': { categoria: "Interface", palavras: ["circulo", "reticencias"] },
  retorno: { categoria: "Navegação", palavras: ["retorno"] },
  reuniao: { categoria: "Usuário", palavras: ["reuniao"] },
  revolut: { categoria: "Bancos", palavras: ["banco", "cambio", "digital", "internacional", "revolut"] },
  rico: { categoria: "Bancos", palavras: ["banco", "corretora", "investimento", "rico"] },
  robo: { categoria: "Tecnologias", palavras: ["robo"] },
  sacola: { categoria: "Comércio", palavras: ["sacola"] },
  safra: { categoria: "Bancos", palavras: ["banco", "safra"] },
  sair: { categoria: "Usuário", palavras: ["sair"] },
  'salao-de-festas': { categoria: "Imóveis", palavras: ["de", "festas", "salao"] },
  salvar: { categoria: "Ações", palavras: ["salvar"] },
  sangue: { categoria: "Corpo & Saúde", palavras: ["sangue"] },
  santander: { categoria: "Bancos", palavras: ["banco", "santander"] },
  sauna: { categoria: "Imóveis", palavras: ["sauna"] },
  scooter: { categoria: "Veículos", palavras: ["scooter"] },
  script: { categoria: "Desenvolvimento", palavras: ["script"] },
  sedan: { categoria: "Veículos", palavras: ["automovel", "carro", "sedan", "veiculo"] },
  seguranca: { categoria: "Segurança", palavras: ["seguranca"] },
  selo: { categoria: "Objetos", palavras: ["selo"] },
  servidor: { categoria: "Dispositivos", palavras: ["dados", "servidor"] },
  seta: { categoria: "Navegação", palavras: ["seta", "seta-direita"] },
  'seta-baixo': { categoria: "Navegação", palavras: ["baixo", "seta"] },
  'seta-baixo-fina': { categoria: "Navegação", palavras: ["baixo", "fina", "seta"] },
  'seta-cima': { categoria: "Navegação", palavras: ["cima", "seta"] },
  'seta-cima-fina': { categoria: "Navegação", palavras: ["cima", "fina", "seta"] },
  'seta-circulo': { categoria: "Navegação", palavras: ["circulo", "seta"] },
  'seta-circulo-cheia': { categoria: "Navegação", palavras: ["cheia", "circulo", "seta"] },
  'seta-curva': { categoria: "Navegação", palavras: ["curva", "seta"] },
  'seta-direita': { categoria: "Navegação", palavras: ["direita", "seta"] },
  'seta-direita-fina': { categoria: "Navegação", palavras: ["direita", "fina", "seta"] },
  'seta-dupla': { categoria: "Navegação", palavras: ["dupla", "seta"] },
  'seta-esquerda': { categoria: "Navegação", palavras: ["esquerda", "seta"] },
  'seta-esquerda-fina': { categoria: "Navegação", palavras: ["esquerda", "fina", "seta"] },
  'seta-fina': { categoria: "Navegação", palavras: ["fina", "seta"] },
  'seta-link': { categoria: "Navegação", palavras: ["link", "seta"] },
  'seta-upload': { categoria: "Navegação", palavras: ["seta", "upload"] },
  setinha: { categoria: "Navegação", palavras: ["seta", "seta-fina", "setinha"] },
  'setinha-baixo': { categoria: "Navegação", palavras: ["baixo", "setinha"] },
  sicoob: { categoria: "Bancos", palavras: ["banco", "cooperativa", "sicoob"] },
  sicredi: { categoria: "Bancos", palavras: ["banco", "cooperativa", "sicredi"] },
  'simbolo-dolar': { categoria: "Financeiro", palavras: ["dinheiro", "dolar", "moeda", "simbolo", "usd"] },
  'simbolo-euro': { categoria: "Financeiro", palavras: ["dinheiro", "euro", "moeda", "simbolo"] },
  'simbolo-real': { categoria: "Financeiro", palavras: ["brasil", "dinheiro", "moeda", "real", "rs", "simbolo"] },
  sincronizar: { categoria: "Ações", palavras: ["sincronizar"] },
  sino: { categoria: "Comunicação", palavras: ["alerta", "aviso", "bell", "lembrete", "notificacao", "sino"] },
  smartwatch: { categoria: "Dispositivos", palavras: ["smartwatch"] },
  sofa: { categoria: "Móveis", palavras: ["sofa"] },
  'sofa-dois': { categoria: "Móveis", palavras: ["dois", "estofado", "movel", "sala", "sofa"] },
  'sofa-tres': { categoria: "Móveis", palavras: ["sofa", "tres"] },
  sol: { categoria: "Clima", palavras: ["claro", "clima", "dia", "light", "sol", "tempo"] },
  solarium: { categoria: "Imóveis", palavras: ["solarium"] },
  sorvete: { categoria: "Comida", palavras: ["sorvete"] },
  stone: { categoria: "Bancos", palavras: ["banco", "maquininha", "pagamento", "stone"] },
  'street-view': { categoria: "Lugares", palavras: ["street", "view"] },
  stripe: { categoria: "Bancos", palavras: ["banco", "gateway", "internacional", "pagamento", "stripe"] },
  subindo: { categoria: "Navegação", palavras: ["subindo"] },
  suv: { categoria: "Veículos", palavras: ["carro", "suv", "utilitario", "veiculo"] },
  taca: { categoria: "Comida", palavras: ["taca", "talheres"] },
  tag: { categoria: "Comércio", palavras: ["tag"] },
  talheres: { categoria: "Comida", palavras: ["talheres"] },
  tamanho: { categoria: "Interface", palavras: ["tamanho"] },
  tapete: { categoria: "Móveis", palavras: ["tapete"] },
  tarefa: { categoria: "Documentos", palavras: ["tarefa"] },
  tarefas: { categoria: "Documentos", palavras: ["tarefas"] },
  teclado: { categoria: "Dispositivos", palavras: ["teclado"] },
  telefone: { categoria: "Comunicação", palavras: ["celular", "chamada", "contato", "fone", "ligacao", "telefone"] },
  tesoura: { categoria: "Objetos", palavras: ["cortar", "recortar", "tesoura"] },
  ticket: { categoria: "Comércio", palavras: ["ticket"] },
  tiktok: { categoria: "Redes Sociais", palavras: ["tiktok"] },
  tomada: { categoria: "Dispositivos", palavras: ["tomada"] },
  tomate: { categoria: "Comida", palavras: ["tomate"] },
  ton: { categoria: "Bancos", palavras: ["banco", "maquininha", "pagamento", "stone", "ton"] },
  toque: { categoria: "Interface", palavras: ["toque"] },
  transferencia: { categoria: "Financeiro", palavras: ["transferencia"] },
  transferencias: { categoria: "Financeiro", palavras: ["transferencias"] },
  transferir: { categoria: "Financeiro", palavras: ["transferir"] },
  transmissao: { categoria: "Comunicação", palavras: ["transmissao"] },
  transporte: { categoria: "Veículos", palavras: ["transporte"] },
  'treino-cinco': { categoria: "Corpo & Saúde", palavras: ["cinco", "treino"] },
  'treino-dois': { categoria: "Corpo & Saúde", palavras: ["dois", "treino"] },
  'treino-quatro': { categoria: "Corpo & Saúde", palavras: ["quatro", "treino"] },
  'treino-seis': { categoria: "Corpo & Saúde", palavras: ["seis", "treino"] },
  'treino-tres': { categoria: "Corpo & Saúde", palavras: ["treino", "tres"] },
  'treino-um': { categoria: "Corpo & Saúde", palavras: ["treino", "um"] },
  triciculo: { categoria: "Veículos", palavras: ["triciculo"] },
  trofeu: { categoria: "Objetos", palavras: ["campeao", "conquista", "ganhar", "premio", "trofeu", "vencedor"] },
  universidade: { categoria: "Educação", palavras: ["universidade"] },
  upload: { categoria: "Ações", palavras: ["carregar", "enviar", "subir", "upload"] },
  usuario: { categoria: "Usuário", palavras: ["avatar", "conta", "perfil", "pessoa", "user", "usuario"] },
  'usuario-adicionar': { categoria: "Usuário", palavras: ["adicionar", "usuario"] },
  'usuario-circulo': { categoria: "Usuário", palavras: ["circulo", "usuario"] },
  usuarios: { categoria: "Usuário", palavras: ["usuarios"] },
  vaca: { categoria: "Animais", palavras: ["vaca"] },
  van: { categoria: "Veículos", palavras: ["furgao", "transporte", "van", "veiculo"] },
  'varinha-magica': { categoria: "Objetos", palavras: ["magica", "varinha"] },
  veia: { categoria: "Corpo & Saúde", palavras: ["veia"] },
  venda: { categoria: "Financeiro", palavras: ["venda"] },
  video: { categoria: "Multimídia", palavras: ["video"] },
  'visao-cards': { categoria: "Interface", palavras: ["cards", "visao"] },
  'visao-lista': { categoria: "Interface", palavras: ["lista", "visao"] },
  'visao-slide': { categoria: "Interface", palavras: ["slide", "visao"] },
  visitas: { categoria: "Usuário", palavras: ["visitas"] },
  whatsapp: { categoria: "Redes Sociais", palavras: ["chat", "contato", "mensagem", "whatsapp", "zap"] },
  'whatsapp-ia': { categoria: "Redes Sociais", palavras: ["ia", "whatsapp"] },
  wifi: { categoria: "Interface", palavras: ["wifi"] },
  wise: { categoria: "Bancos", palavras: ["banco", "cambio", "internacional", "transferencia", "wise"] },
  wordpress: { categoria: "Tecnologias", palavras: ["blog", "cms", "site", "tech", "tech-wordpress", "wordpress", "wp"] },
  x: { categoria: "Interface", palavras: ["cancelar", "close", "erro", "fechar", "remover", "sair", "x"] },
  'x-fino': { categoria: "Interface", palavras: ["fino", "x"] },
  'x-redondo': { categoria: "Interface", palavras: ["redondo", "x"] },
  xp: { categoria: "Bancos", palavras: ["banco", "corretora", "investimento", "xp"] },
  yoga: { categoria: "Educação", palavras: ["yoga"] },
  youtube: { categoria: "Redes Sociais", palavras: ["youtube"] },
  'zoom-mais': { categoria: "Ações", palavras: ["mais", "zoom"] },
  'zoom-menos': { categoria: "Ações", palavras: ["menos", "zoom"] }
}
